# Generated by Django 2.0 on 2018-02-01 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diabetes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='time',
            field=models.DateTimeField(),
        ),
    ]
