# Generated by Django 2.0 on 2018-02-01 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diabetes', '0002_auto_20180201_0538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='patients',
            field=models.ManyToManyField(blank=True, null=True, related_name='doctors', to='diabetes.Profile'),
        ),
    ]
