# Generated by Django 2.0 on 2018-02-01 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diabetes', '0004_auto_20180201_0555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='notes',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='patients',
            field=models.ManyToManyField(blank=True, related_name='doctors', to='diabetes.Profile'),
        ),
    ]
