# Generated by Django 2.0 on 2018-02-01 02:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diabetes', '0004_auto_20180201_0555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reading',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to=settings.AUTH_USER_MODEL),
        ),
    ]
