# Generated by Django 2.0 on 2018-02-01 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diabetes', '0005_auto_20180201_0556'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reading',
            old_name='patient',
            new_name='user',
        ),
    ]
