# Generated by Django 2.0 on 2018-02-01 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diabetes', '0008_merge_20180201_0608'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reading',
            name='patient',
        ),
    ]
